services:
  db:
    container_name: database
    image: postgres:latest
    environment:
      - POSTGRES_USER= ${POSTGRES_USER}
      - POSTGRES_PASSWORD= ${POSTGRES_PASSWORD}
      - POSTGRES_DB= ${POSTGRES_DB}
      - POSTGRES_PORT= ${POSTGRES_PORT}
    volumes:
      - ./sql/databases.sql:/docker-entrypoint-initdb.d/1.databases.sql
      - ./AccountService/sql/schema.sql:/docker-entrypoint-initdb.d/2.schema.sql
      - ./AccountService/sql/data.sql:/docker-entrypoint-initdb.d/3.data.sql
      - ./WorkoutService/sql/schema.sql:/docker-entrypoint-initdb.d/4.schema.sql
      - ./WorkoutService/sql/data.sql:/docker-entrypoint-initdb.d/5.data.sql

  app:
    container_name: app
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    build: .
    env file: .env
    depends_on:
      - db
